---
- name: create nginx.conf
  template:
    src: nginx.conf.j2
    dest: "{{ nginx_conf_dir }}/nginx.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nginx
  tags:
    - nginx
    - nginx_config
