---
- name: start nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: stop nginx
  service:
    name: nginx
    state: stopped

- name: restart nginx
  service:
    name: nginx
    state: restarted
